palantir/conjure

readme.md

There was a dead link to conjure-python-runtime
The link now points to conjure-python-client

docs: Correct link to conjure-python-client

---

docs/spec/conjure_definitions.md
docs/spec/wire.md

Argument definition spec did not document the default behaviour and wire spec examples were not correct.
The spec has been corrected

[fix] Fix arguments spec

---

docs/getting_started.md

Users exactly following the getting started guide would be unable to resolve all their build script dependencies and would get a very confusing error.
Users following the getting started guide should no longer encounter any issues.
Thanks to MrFantastik from Lobster for [point this out](https://lobste.rs/s/egbgwb/introducing_conjure_palantir_s#c_vzpbkj)

[fix] Fix getting started build.gradle

---

conjure-core/src/main/java/com/palantir/conjure/defs/validator/HttpPathValidator.java
conjure-core/src/main/java/com/palantir/conjure/parser/services/PathString.java
conjure-core/src/test/java/com/palantir/conjure/defs/validator/HttpPathValidatorTest.java
conjure-core/src/test/java/com/palantir/conjure/parser/services/ServiceDefinitionTests.java
conjure-core/src/test/resources/spec-tests/endpoint_path_args.yml
docs/spec/conjure_definitions.md

IR compilation would break if a service endpoint have a path definition of `some/v1.2/path`
Allows `.`s in the path, fixes #177 
@iamdanfox

[improvement] Allow dots in endpoint paths

---

conjure-core/src/main/java/com/palantir/conjure/parser/types/names/FieldName.java

Single character field names were not allowed (eg: `Point { x, y }`)
Allows single character field names.

[improvement] Allow single character field names

---

conjure-core/src/main/java/com/palantir/conjure/parser/types/names/FieldName.java
conjure-core/src/test/java/com/palantir/conjure/defs/validator/FieldNameValidatorTest.java
conjure-generator-common/src/main/java/com/palantir/conjure/CaseConverter.java

There were 2 validations for field names.  A previous PR attempted to allow single character field names, but there were 2 places validations happened.
Allow single character field names and prevent the issue from happening again by having only 1 source of truth for the validation patterns.

[fix] Get rid of the patterns in FieldName to allow single character field names

---

docs/spec/conjure_definitions.md

We did not have any documentation on the `deprecated` field on endpoint definitions
Now we do!

[fix] add docs on endpoint deprecation

---

conjure-core/src/main/java/com/palantir/conjure/defs/validator/EndpointDefinitionValidator.java
conjure-core/src/test/java/com/palantir/conjure/defs/validator/ArgumentNameValidatorTest.java
conjure-core/src/test/java/com/palantir/conjure/defs/validator/EndpointDefinitionTest.java
conjure-core/src/test/java/com/palantir/conjure/defs/validator/ParamIdValidatorTest.java
conjure-core/src/test/resources/spec-tests/endpoint_body_args.yml
conjure-core/src/test/resources/spec-tests/endpoint_path_args.yml

Previously it was difficult to tell which endpoint caused validation
to fail.
==COMMIT_MSG==
EndpointDefinition validation errors include the endpoint name and path
==COMMIT_MSG==

[improvement] EndpointDefinition validation errors include the endpoint name and path

---

docs/spec/conjure_definitions.md

The spec does not reflect the intent and the reality as per https://github.com/palantir/conjure/blob/master/conjure-core/src/main/java/com/palantir/conjure/defs/validator/EndpointDefinitionValidator.java .
The spec matches the intent and the reality as per https://github.com/palantir/conjure/blob/master/conjure-core/src/main/java/com/palantir/conjure/defs/validator/EndpointDefinitionValidator.java .

[Fix] Clarify what parameter types are allowed for path/query/header

---

conjure-core/src/main/java/com/palantir/conjure/defs/validator/EndpointDefinitionValidator.java
conjure-core/src/test/java/com/palantir/conjure/defs/validator/ArgumentNameValidatorTest.java
conjure-core/src/test/java/com/palantir/conjure/defs/validator/ParamIdValidatorTest.java

Fixes #48
Validation for query parameters is more strict than for JSON field names.
Endpoint validation allows legacy kebab-case and snake_case query params but logs a warning.
New APIs may accidentally use legacy argument formats. This is mitigated with a logged warning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/conjure/299)

[improvement] Allow legacy kebab-case and snake_case query params

---

docs/spec/conjure_definitions.md

Appears as though this is no longer a part of [`ArugmentDefinition`](https://github.com/palantir/conjure/blob/master/conjure-core/src/main/java/com/palantir/conjure/parser/services/ArgumentDefinition.java)

Updated docs to remove deprecated from argument

---

conjure-core/src/main/java/com/palantir/conjure/defs/Conjure.java
conjure-core/src/main/java/com/palantir/conjure/parser/NormalizeDefinition.java
conjure-core/src/test/java/com/palantir/conjure/parser/NormalizeDefinitionTest.java
conjure-core/src/test/resources/normalize-me.yml
conjure-core/src/test/resources/normalized.conjure.json

As mentioned in https://github.com/palantir/conjure/issues/316, within the List<TypeDefinition>, the order was actually undefined.
==COMMIT_MSG==
The conjure CLI will always emit IR with types, services and errors sorted alphabetically by their type name.
We don't sort endpoints or arguments within these definitions, instead prefer to preserve the original source ordering.
==COMMIT_MSG==
fixes https://github.com/palantir/conjure/issues/316
cc @bmoylan

[fix] Emit IR with types, services and errors sorted by type name

---

conjure-api/src/main/conjure/conjure-api.yml
docs/spec/conjure_definitions.md
docs/spec/wire.md

Palantir's authentication service uses 401 in the expected way, but currently clients have to manually propagate these. This PR makes 401 part of the conjure spec, which will let us define it as an `ErrorType` in conjure-java-runtime-api and propagate by default in conjure-java-runtime, similar to 403s.
HTTP names this 401 Unauthorized, however 401 Unauthenticated seems like a clearer name given the way Palantir uses 401s, and to avoid confusion with 403 PermissionDenied.

Add 401 Unauthenticated to conjure error types

---

changelog/@unreleased/pr-422.v2.yml
conjure-core/src/main/java/com/palantir/conjure/defs/validator/UnionDefinitionValidator.java

`type` was an acceptable union variant name, but we have no idea how to serialize it to JSON. We can't use `"type"` as that's already reserved for the chosen union variant name.
This edge case is not mentioned in [the yml definition spec](https://palantir.github.io/conjure/#/docs/spec/conjure_definitions?id=uniontypedefinition) nor in [the wire format](https://palantir.github.io/conjure/#/docs/spec/wire?id=_54-union-json-format).
==COMMIT_MSG==
Don't allow a union variant called `type` as we don't know how that should be serialized.
==COMMIT_MSG==
Fixes #179.
People might have come up with a format for how to serialize this edge case in a particular generator only (e.g. go, rust?) that didn't make it back to the spec, in which case we'd break those use cases.

Fix: Don't allow a union variant called 'type'

---

changelog/@unreleased/pr-423.v2.yml
conjure-core/src/main/java/com/palantir/conjure/defs/validator/ConjureDefinitionValidator.java
conjure-core/src/test/java/com/palantir/conjure/defs/validator/ConjureSourceFileValidatorTest.java

==COMMIT_MSG==
Validate map keys have PLAIN representation
Previously it was possible to build a conjure definition for a
map that was impossible to serialize as JSON. If this fails
on an external type import, please make sure you have
selected the most accurate fallback type value, the default
`any` is not allowed.
==COMMIT_MSG==

Fix #325: Validate map keys have PLAIN representation

---

docs/spec/wire.md

`any` was documented to only representing primitive and object values.
==COMMIT_MSG==
`any`'s specification has been clarified to allow lists of `any` values.
==COMMIT_MSG==

Allow lists in `any` values

---

changelog/@unreleased/pr-497.v2.yml
conjure-core/src/main/java/com/palantir/conjure/defs/validator/EndpointDefinitionValidator.java
conjure-core/src/test/java/com/palantir/conjure/defs/validator/EndpointDefinitionTest.java
conjure-core/src/test/resources/spec-tests/services.yml

Query and header parameters using `list<binary>` `set<binary>` and `optional<binary>` types incorrectly passed validation.
==COMMIT_MSG==
Validate against binary data in non-body container parameters.
==COMMIT_MSG==

Fix #491: Validate against binary data in non-body container parameters

---

changelog/@unreleased/pr-494.v2.yml
conjure-api/src/main/conjure/conjure-api.yml
conjure-core/src/main/java/com/palantir/conjure/defs/ConjureParserUtils.java
conjure-core/src/main/java/com/palantir/conjure/parser/types/complex/EnumValueDefinition.java
conjure-core/src/main/java/com/palantir/conjure/parser/types/complex/FieldDefinition.java
conjure-core/src/test/java/com/palantir/conjure/defs/validator/ConjureSourceFileValidatorTest.java
conjure-core/src/test/java/com/palantir/conjure/parser/ConjureParserTest.java
conjure-core/src/test/java/com/palantir/conjure/validator/FieldDefinitionValidatorTest.java
conjure-core/src/test/resources/example-deprecation.yml
conjure-core/src/test/resources/normalized.conjure.json
docs/spec/conjure_definitions.md
docs/spec/intermediate_representation.md

No deprecation docs on fields, union types, or enum values.
==COMMIT_MSG==
Enum values, fields, and union values support deprecation documentation.
==COMMIT_MSG==
This is an additive change to the intermediate representation,
however there is little risk for consumers because this information
is simple metadata.

Fix #120: Enum values, fields, and union values support deprecation

---

docs/spec/conjure_definitions.md

Deprecation applies to union and enum variants, not the top-level types.

Fix deprecated docs

---

changelog/@unreleased/pr-533.v2.yml
conjure/src/main/java/com/palantir/conjure/cli/ConjureCli.java
conjure/src/test/java/com/palantir/conjure/cli/ConjureCliTest.java

Conjure CLI would barf if any unknown options were provided. This made adding a new option require a lockstep upgrade between the CLI and the build tooling that would populate the option
==COMMIT_MSG==
Conjure CLI will log and ignore any unknown options that are provided
==COMMIT_MSG==
N/A

Conjure CLI is permissive with unknown options

---

changelog/@unreleased/pr-537.v2.yml
conjure-core/src/main/java/com/palantir/conjure/defs/Conjure.java
conjure-core/src/main/java/com/palantir/conjure/defs/ConjureParserUtils.java
conjure-core/src/main/java/com/palantir/conjure/parser/AnnotatedConjureSourceFile.java
conjure-core/src/main/java/com/palantir/conjure/parser/ConjureParser.java
conjure-core/src/test/java/com/palantir/conjure/defs/ConjureDefTest.java
conjure-core/src/test/java/com/palantir/conjure/defs/ConjureSpecTest.java

If your conjure definition file failed validation, the old error message would not tell you what file the error was in:
```
java.lang.IllegalStateException: Endpoint 'testEndpoint{http: GET /path}' cannot have multiple body parameters: [arg, arg2]
```
==COMMIT_MSG==
Errors encountered when parsing or validating conjure definition files will now tell you which file the error was found in.
==COMMIT_MSG==
The error now looks like:
```
java.lang.RuntimeException: Encountered error trying to parse file 'test'
// stacktrace
Caused by: java.lang.IllegalStateException: Endpoint 'testEndpoint{http: GET /path}' cannot have multiple body parameters: [arg, arg2]
```
More complicated code.

Better error message telling you which file the error came from

---

docs/spec/conjure_definitions.md

Endpoint markers have been deprecated since the release of OSS conjure (?), and certainly aren't supported in conjure-java (see https://github.com/palantir/conjure-java/pull/883)
==COMMIT_MSG==
Misleading documentation about endpoint markers is removed
==COMMIT_MSG==

remove endpoint marker documentation

---

changelog/@unreleased/pr-667.v2.yml
conjure-core/src/main/java/com/palantir/conjure/defs/Conjure.java
conjure-core/src/main/java/com/palantir/conjure/parser/ConjureParser.java

Parsed results were not cached between runs, so certain common files could be parsed many times in a single run.
==COMMIT_MSG==
Each conjure file will only be parsed once
==COMMIT_MSG==
The code is no longer thread safe due to sharing of a static HashMap across threads, but the cli is single-threaded.

cache parsed results across multiple runs

---

changelog/@unreleased/pr-675.v2.yml
conjure/src/main/java/com/palantir/conjure/cli/ConjureCli.java

Due to an upgrade of picocli we would swallow errors and always exit 0
==COMMIT_MSG==
correctly set exit code on failure.
==COMMIT_MSG==

fix: correctly set exit code on failure

---

changelog/@unreleased/pr-702.v2.yml
conjure-api/src/main/conjure/conjure-api.yml
conjure-core/src/main/java/com/palantir/conjure/defs/ConjureParserUtils.java
conjure-core/src/main/java/com/palantir/conjure/parser/services/ArgumentDefinition.java
conjure-core/src/main/java/com/palantir/conjure/parser/services/EndpointDefinition.java
conjure-core/src/test/java/com/palantir/conjure/parser/services/ServiceDefinitionTests.java
conjure-core/src/test/resources/normalized.conjure.json
conjure-core/src/test/resources/test-service.yml
docs/spec/conjure_definitions.md

Closes #612
users were able to annotate endpoints with type `markers` which was used by Java generator to apply annotations to endpoints or to indicate to the generator to different endpoint signatures (ex. Java-undertow and `Async` type). This was problematic since the type based approach limited the usefulness of markers to Java projects as well as prevented users from adding metadata to their definitions that could be used non-generator consumers of the IR (i.e. Documentation services)
==COMMIT_MSG==
Add `tags` field to `EndpointDefinition` in the IR
==COMMIT_MSG==
Any values provided in this field must not impact the wire structure of the endpoint and should not be considered when evaluating backwards compatability.
Duplicated functionality with `markers` could be confusing and the …

feature: add per endpoint tags

---

changelog/@unreleased/pr-736.v2.yml
conjure-api/src/main/conjure/conjure-api.yml

==COMMIT_MSG==
tags are consistently sets
==COMMIT_MSG==

fix: tags are consistently sets

---

docs/spec/conjure_definitions.md

The following exception would occur whilst compiling the example.
```
com.palantir.logsafe.exceptions.SafeIllegalArgumentException: Unrecognized definition, types must have either fields, values or an alias defined.
```
When compiling just the example.yml and common.yml there is a NullPointerException, but at least the definition can be parsed properly.

Fix conjure-imports example in conjure_definitions.md 

---

changelog/@unreleased/pr-804.v2.yml
conjure-core/src/main/java/com/palantir/conjure/parser/types/names/TypeName.java
conjure-core/src/test/java/com/palantir/conjure/parser/types/TypeParserTests.java

```
Caused by: java.lang.IllegalArgumentException: TypeNames must be a primitive type [any, string, integer, double, boolean, safelong, rid, bearertoken, uuid] or match pattern ^[A-Z][a-z0-9]+([A-Z][a-z0-9]+)*$: bytes
``` 
when use invalid type `bytes`, i got that error message on `classpath 'com.palantir.gradle.conjure:gradle-conjure:5.1.1'`. It's missing `binary` and `datetime` 
==COMMIT_MSG==
Includes binary and datetime in suggested built-in types in the error message of invalid type. 
==COMMIT_MSG==

Update error message of invalid type

---

changelog/@unreleased/pr-814.v2.yml
conjure-core/src/main/java/com/palantir/conjure/parser/types/TypeParser.java
conjure-core/src/main/java/com/palantir/parsec/ParseException.java
conjure-core/src/main/java/com/palantir/parsec/Parsers.java
conjure-core/src/test/java/com/palantir/conjure/parser/types/TypeParserTests.java
conjure-core/src/test/java/com/palantir/parsec/tests/TestUnitParsers.java

This is a recreation of #814 without a fork, allowing circle builds to run.
When an exception is hit while performing `Parser.or`, the exception is immediately thrown. Additionally, this current behaviour is causing tests to fail on master.
==COMMIT_MSG==
Change behaviour of `or` parser to instead store any exceptions, and re-throw it as a `ParseException` if no parser successfully completes.
==COMMIT_MSG==

Add behaviour to the 'or' parser to pass through errors

---

changelog/@unreleased/pr-835.v2.yml
conjure-core/src/main/java/com/palantir/conjure/defs/validator/EndpointDefinitionValidator.java
conjure-core/src/test/java/com/palantir/conjure/defs/validator/ParamIdValidatorTest.java

Conjure users can set headers that we use for the low level protocol.
==COMMIT_MSG==
Users can no longer set protocol headers (Host, Accept, Content-Type).
==COMMIT_MSG==
Someone is relying on this already?

Validate conjure headers do not set protocol headers.

---

.circleci/config.yml
CONTRIBUTING.md
changelog/@unreleased/pr-848.v2.yml
readme.md

https://www.getpostman.com/ has too large of a header for the `liche` checks. It doesn't look like there's a way to easily expand the read headers (that I can see), so I just combined the postman-collections link into one.
Example of failing build caused by this: https://app.circleci.com/pipelines/github/palantir/conjure/1132/workflows/8965f3da-1ad6-42bc-b4d4-1365648a2247/jobs/9751
==COMMIT_MSG==
Remove docs link to https://www.getpostman.com/ so builds pass again.
==COMMIT_MSG==

Fix broken liche checks

---

changelog/@unreleased/pr-873.v2.yml
conjure-core/src/main/java/com/palantir/conjure/defs/ConjureParserUtils.java
conjure-core/src/main/java/com/palantir/conjure/defs/ConjureTypeParserVisitor.java
conjure-core/src/main/java/com/palantir/conjure/defs/validator/ConjureDefinitionValidator.java
conjure-core/src/main/java/com/palantir/conjure/defs/validator/EndpointDefinitionValidator.java
conjure-core/src/main/java/com/palantir/conjure/defs/validator/FieldDefinitionValidator.java
conjure-core/src/main/java/com/palantir/conjure/exceptions/ConjureException.java
conjure-core/src/main/java/com/palantir/conjure/exceptions/ConjureIllegalArgumentException.java
conjure-core/src/main/java/com/palantir/conjure/exceptions/ConjureIllegalStateException.java
conjure-core/src/main/java/com/palantir/conjure/exceptions/ConjureRuntimeException.java
conjure/src/main/java/com/palantir/conjure/cli/ConjureCli.java
conjure/src/test/java/com/palantir/conjure/cli/ConjureCliTest.java
conjure/src/test/resources/key-error.yml
conjure/src/test/resources/simple-error.yml

Error messages can become unreadable:
<details>
<summary>Stderr before PR:</summary>
```
com.palantir.conjure.exceptions.ConjureRuntimeException: Encountered error trying to parse file 'src/test/resources/simple-error.yml'
at com.palantir.conjure.defs.ConjureParserUtils.lambda$parseConjureDef$3(ConjureParserUtils.java:230)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.palantir.conjure.defs.ConjureParserUtils.parseConjureDef(ConjureParserUtils.java:201)
at com.palantir.conjure.defs.Conjure.parse(Conjure.java:37)
at com.palantir.conjure.cli.ConjureCli$CompileCommand.generate(ConjureCli.java:144)
at com.palantir.conjure.cli.ConjureCli$CompileCommand.run(ConjureCli.java:138)
at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
at …
```

Clean up error message from CLI

---

changelog/@unreleased/pr-874.v2.yml
conjure-core/src/main/java/com/palantir/conjure/defs/validator/ConjureDefinitionValidator.java
conjure/src/main/java/com/palantir/conjure/cli/ConjureCli.java
conjure/src/test/java/com/palantir/conjure/cli/ConjureCliTest.java
conjure/src/test/resources/unique-name-error/unique-name-error-2.yml
conjure/src/test/resources/unique-name-error/unique-name-error.yml

<details>
<summary>Before</summary>
Note that in real cases this is quite a bit more obnoxious, as the first list contains all types that have been processed until then. In large code-bases this can be substantial.
```
com.google.common.base.VerifyException: Type, error, and service names must be unique across locally defined and imported types/errors: [TypeName{name: UniqueName, package: test.api}, TypeName{name: UniqueName2, package: test.api}, TypeName{name: ConflictingName, package: test.api}]
TypeName{name: ConflictingName, package: test.api}
at com.google.common.base.Verify.verify(Verify.java:424)
at com.palantir.conjure.defs.validator.ConjureDefinitionValidator$UniqueNamesValidator.verifyNameIsUnique(ConjureDefinitionValidator.java:117)
at …
```

Cleanup duplicate name error

---

changelog/@unreleased/pr-875.v2.yml
conjure-core/src/main/java/com/palantir/conjure/parser/ConjureParser.java
conjure-core/src/test/java/com/palantir/conjure/parser/ConjureParserTest.java
conjure/src/main/java/com/palantir/conjure/cli/ConjureCli.java
conjure/src/test/java/com/palantir/conjure/cli/ConjureCliTest.java
conjure/src/test/resources/invalid-json.yml

<details>
<summary>Before</summary>
Note the absence of a reference to which file failed.
```
java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Cannot build FieldDefinition, some of required attributes are not set [type] (through reference chain: com.palantir.conjure.parser.ImmutableConjureSourceFile$Json["types"]->com.palantir.conjure.parser.types.ImmutableTypesDefinition$Json["definitions"]->com.palantir.conjure.parser.types.ImmutableNamedTypesDefinition$Json["objects"]->java.util.LinkedHashMap["InvalidJson"]->com.palantir.conjure.parser.types.complex.ImmutableUnionTypeDefinition$Json["union"]->java.util.LinkedHashMap["optionA"])
at com.palantir.conjure.parser.ConjureParser$RecursiveParser.parseInternal(ConjureParser.java:133)
at …
```

Clean up JSON mapping errors

---

docs/getting_started.md
docs/howto/invoke_clis_manually.md

bintray is dead
==COMMIT_MSG==
move bintray reference to maven central
==COMMIT_MSG==

improvement: move bintray reference to maven central

---

docs/getting_started.md

The docs use the removed `compile` Gradle configuration.
The docs use the `implementation` Gradle configuration.

Update docs for Gradle 7

---

changelog/@unreleased/pr-1099.v2.yml
conjure-core/src/main/java/com/palantir/conjure/parser/types/TypeParser.java
conjure-core/src/main/java/com/palantir/parsec/ParseException.java
conjure-core/src/main/java/com/palantir/parsec/ParserState.java
conjure-core/src/main/java/com/palantir/parsec/Parsers.java
conjure-core/src/main/java/com/palantir/parsec/StringParserState.java
conjure-core/src/main/java/com/palantir/parsec/parsers/BetweenParser.java
conjure-core/src/main/java/com/palantir/parsec/parsers/DefaultingDispatchingParser.java
conjure-core/src/test/java/com/palantir/conjure/parser/ImportSetPrefixTest.java
conjure-core/src/test/resources/import-set-prefix-target.yml
conjure-core/src/test/resources/import-set-prefix.yml

Previously importing conjure objects using a reference along the
lines of `settings.Foo` would fail because it would match the
`set` prefix. Now we handle it correctly.
This introduces a change to the way parser markers work:
Instead of maintaining a mark/rewind/release stack, the mark
method returns an object which can be used to return to the
marked location, and the `release` functionality is no longer
necessarily. This takes advantage of the application stack
rather than maintaining a separate stack that can get out of
sync.
==COMMIT_MSG==
Fix references with container prefixes `set`/`list`/`optional`
==COMMIT_MSG==

Fix references with container prefixes `set`/`list`/`optional`

---

changelog/@unreleased/pr-1140.v2.yml
conjure-api/build.gradle
conjure-api/src/main/conjure/conjure-api.yml
conjure-core/src/main/java/com/palantir/conjure/defs/ConjureParserUtils.java
conjure-core/src/main/java/com/palantir/conjure/defs/validator/ConjureDefinitionValidator.java
conjure-core/src/main/java/com/palantir/conjure/defs/validator/ErrorDefinitionValidator.java
conjure-core/src/main/java/com/palantir/conjure/defs/validator/SafetyValidator.java
conjure-core/src/main/java/com/palantir/conjure/parser/LogSafetyDefinition.java
conjure-core/src/main/java/com/palantir/conjure/parser/types/complex/FieldDefinition.java
conjure-core/src/main/java/com/palantir/conjure/parser/types/reference/AliasTypeDefinition.java
conjure-core/src/test/java/com/palantir/conjure/defs/validator/ConjureSourceFileValidatorTest.java
conjure-core/src/test/java/com/palantir/conjure/defs/validator/EndpointDefinitionTest.java
conjure-core/src/test/resources/normalized.conjure.json
docs/spec/conjure_definitions.md

No real concept of safety aside from hand-waving in ErrorDefinition.
==COMMIT_MSG==
Conjure types may be declared with log-safety. Only conjure primitives (and wrappers around these primitives) may declare safety, complex types calculate safety based on the type graph.
==COMMIT_MSG==
`Map` is not supported at this point, unless the keys and values are wrapped with some other type (Alias).
The current implementation doesn't support declaring safety of external type imports, they're a bit harder to handle due to to lack of information when the IR is compiled.

Conjure types may be declared with log-safety

---

docs/spec/conjure_definitions.md

==COMMIT_MSG==
Add missing section link to `LogSafety` documentation
==COMMIT_MSG==

Add missing section link to `LogSafety` documentation

---

changelog/@unreleased/pr-1170.v2.yml
conjure-core/src/main/java/com/palantir/conjure/defs/validator/ConjureDefinitionValidator.java
conjure-core/src/main/java/com/palantir/conjure/defs/validator/SafetyValidator.java
conjure-core/src/test/java/com/palantir/conjure/defs/validator/ConjureSourceFileValidatorTest.java

Having the following incorrect conjure def for safety:
```
SomeWrapperForAnAlias:
safety: unsafe
alias: SomeAlias
SomeAlias:
alias: string
```
results in the error `package.SomeAlias cannot declare log safety. Only conjure primitives and wrappers around conjure primitives may declare safety.` 
SomeAlias isn't the type declaring safety here.
error message becomes `package.SomeWrapperForAnAlias cannot declare log safety. Only conjure primitives and wrappers around conjure primitives may declare safety. package.AliasName is not a primitive type.`
==COMMIT_MSG==
Improve incorrect safety usage error message to reference proper type.
==COMMIT_MSG==
I wanted a way to reference the field name as well so that if you have 
```
ComplexObject:
fields:
field1:
safety: unsafe
type: NonPrimitiveType
... …
```

Better error message for incorrect usage of the safety field

---

changelog/@unreleased/pr-1204.v2.yml
conjure-core/src/main/java/com/palantir/conjure/defs/validator/ConjureDefinitionValidator.java
conjure-core/src/test/java/com/palantir/conjure/defs/validator/ConjureSourceFileValidatorTest.java

Previously there were confusing errors when the same safety was
defined twice on the same argument (via generators), and more
confusion when some arguments weren't flagged due to indirect
safety declarations. Now we require standardization on the
`safety` field, and no safety tags/markers when `requireSafety`
is enabled.
==COMMIT_MSG==
The `--requireSafety` parameter disallows legacy safety formats
==COMMIT_MSG==

The `--requireSafety` parameter disallows legacy safety formats

---

changelog/@unreleased/pr-1249.v2.yml
conjure-core/src/main/java/com/palantir/conjure/defs/validator/ConjureDefinitionValidator.java
conjure-core/src/main/java/com/palantir/conjure/defs/validator/SafetyValidator.java

Migrating an existing Conjure definition to add safety declarations is a bit cumbersome because only one error is reported at a time. When going through a Conjure definition, it's easy to miss some of the places where safety declarations are required, especially because not all types/arguments accept safety declarations.
Conjure compilation will collect and report all safety violations instead of throwing an errors as soon as a single violation is discovered. This should make it much easier to users to find all the places that are missing safety declarations.

Report all safety violations

---

changelog/@unreleased/pr-1273.v2.yml
conjure.schema.json

Right now this complains on e.g. ACCUMULATOR_V2 because it doesn't like the 2. The replacement is the actual validation that Conjure does.

UpperCase should allow numbers

---

changelog/@unreleased/pr-1291.v2.yml
conjure-core/src/main/java/com/palantir/conjure/defs/validator/ConjureDefinitionValidator.java
conjure/src/test/java/com/palantir/conjure/cli/ConjureCliTest.java

Error is quite obscure: 
`Illegal map key found in object Object in field Field`
==COMMIT_MSG==
Improve invalid key map errors to explain map keys can only be primitive Conjure types.
==COMMIT_MSG==

Improve invalid key map errors

---

conjure-generator-common/src/main/java/com/palantir/conjure/CaseConverter.java
conjure-generator-common/src/test/java/com/palantir/conjure/CaseConverterTest.java

When attempting to build graphql schema with a field element of `egressCIDRs` this error message appears:
```
Unexpected case for: egressCIDRs
```
I was confused what this meant, and thought it was related to an unhandled switch-case entry.  Instead, it's actually a problem that `egressCIDRs` isn't in a standard casing for conjure, and I fixed by renaming the graphql field to `egressCidrs`.
==COMMIT_MSG==
Improve error message for failed case conversion
==COMMIT_MSG==
The new message is:
```
Unexpected case for: 'myCIDRs'. Expected one to be in one of these case formats: [LOWER_CAMEL_CASE, KEBAB_CASE, SNAKE_CASE]
```
When seeing this, I think I would've been clued in to changing `egressCIDRs` -> `egressCidrs`
Throwing this exception is slightly more expensive now, but this ought not be in …

Improve error message for failed case conversion

---

changelog/@unreleased/pr-1448.v2.yml
conjure-core/src/main/java/com/palantir/conjure/defs/validator/ConjureDefinitionValidator.java
conjure-core/src/test/java/com/palantir/conjure/defs/validator/ConjureSourceFileValidatorTest.java

One of the examples of: https://github.com/palantir/conjure/issues/1447
Map key validation didn't recursively look inside map value types correctly.
Now it does check inside the map value.
==COMMIT_MSG==
Fixing map key validation
==COMMIT_MSG==

Fixing map key validation

---

changelog/@unreleased/pr-1554.v2.yml
conjure-api/build.gradle

[TS publishing is failing on develop](https://app.circleci.com/jobs/github/palantir/conjure/15409) due to `429 Too Many Requests - PUT https://registry.npmjs.org/...` Turns out though that this [package hasn't successfully published in years](https://www.npmjs.com/package/conjure-api?activeTab=versions).
Disables the TS publish task so that we can continue publishing the _very_ used java bindings.
Kicks the can down the road, we will need to explore CI image upgrades.

Temporarily Disable TS Publishing

---

changelog/4.44.0/pr-1554.v2.yml
changelog/@unreleased/pr-1560.v2.yml
conjure-api/build.gradle

This reverts commit de91900510b3149aca5c69af68de74bd901b448c.
==COMMIT_MSG==
Re-enable typescript publishing
==COMMIT_MSG==

Revert "Temporarily Disable TS Publishing (#1554)"

---

conjure-api/build.gradle
docs/howto/publish_typescript_to_npm.md

We assumed the npmrc location and contents, but they changed long ago.
`generateNpmRc` has configuration points to provide a token directly.

Setup NPM Token using generateNpmRc Task

---

changelog/@unreleased/pr-1570.v2.yml
conjure-core/src/main/java/com/palantir/conjure/parser/services/ServiceDefinition.java
conjure-core/src/test/java/com/palantir/conjure/defs/ConjureDefTest.java
conjure-core/src/test/resources/nameless-test-service.yml
conjure.schema.json
docs/spec/conjure_definitions.md

`ServiceDefinition.name` has been deprecated for 6 years.
==COMMIT_MSG==
ServiceDefinition name field may be omitted
==COMMIT_MSG==

ServiceDefinition name field may be omitted

---

conjure-core/src/main/java/com/palantir/conjure/parser/ConjureParser.java

When compiling the repository, we get these warnings:
```
> Task :conjure-core:javadoc
/Volumes/git/conjure/conjure-core/src/main/java/com/palantir/conjure/parser/ConjureParser.java:80: warning: invalid input: '&'
* Parse file & all imports (recursively).
^
/Volumes/git/conjure/conjure-core/src/main/java/com/palantir/conjure/parser/ConjureParser.java:87: warning: invalid input: '&'
* Parse all files & imports (breadth-first).
^
/Volumes/git/conjure/conjure-core/src/main/java/com/palantir/conjure/parser/ConjureParser.java:80: warning: invalid input: '&'
* Parse file & all imports (recursively).
^
/Volumes/git/conjure/conjure-core/src/main/java/com/palantir/conjure/parser/ConjureParser.java:87: warning: invalid input: '&'
* Parse all files & imports (breadth-first).
^ …
```

nit: Update javadoc to use literal ampersands

---

changelog/@unreleased/pr-1685.v2.yml
conjure-core/src/main/java/com/palantir/conjure/defs/validator/ConjureDefinitionValidator.java
conjure-core/src/test/java/com/palantir/conjure/defs/validator/ConjureSourceFileValidatorTest.java

No validation that the same error name wasn't used in multiple definitions. Over the wire, clients cannot distinguish between multiple errors when the namespace and name (excluding package) match.
==COMMIT_MSG==
Enforce that Conjure error definitions are unique
==COMMIT_MSG==
This could prevent some repos from rolling out changes if they already have duplicate errors. However this is fairly unlikely, and the failure is self-documenting.

Enforce that Conjure error definitions are unique

---

changelog/@unreleased/pr-1670.v2.yml
conjure-api/src/main/conjure/conjure-api.yml
conjure-core/src/main/java/com/palantir/conjure/defs/ConjureParserUtils.java
conjure-core/src/main/java/com/palantir/conjure/defs/EndpointErrorResolver.java
conjure-core/src/main/java/com/palantir/conjure/defs/validator/EndpointDefinitionValidator.java
conjure-core/src/main/java/com/palantir/conjure/parser/services/EndpointDefinition.java
conjure-core/src/main/java/com/palantir/conjure/parser/services/EndpointError.java
conjure-core/src/test/java/com/palantir/conjure/defs/ConjureDefTest.java
conjure-core/src/test/java/com/palantir/conjure/defs/validator/EndpointDefinitionTest.java
conjure-core/src/test/java/com/palantir/conjure/parser/services/ServiceDefinitionTests.java
conjure-core/src/test/resources/example-imported-endpoint-error.yml
conjure-core/src/test/resources/example-non-existent-endpoint-error.yml
conjure-core/src/test/resources/example-non-reference-endpoint-error.yml
conjure-core/src/test/resources/normalized.conjure.json
conjure-core/src/test/resources/spec-tests/services.yml
conjure-core/src/test/resources/test-service.yml
conjure.schema.json
conjure/src/test/resources/test-service.yml
docs/spec/conjure_definitions.md
docs/spec/intermediate_representation.md

Expand the Conjure specification to support specifying errors that can be thrown on each endpoint.
This work is a revival of the ideas outlined in [RFC-007](https://github.com/palantir/conjure/blob/master/docs/rfc/007-endpoint-errors.md) and #816.
* Conjure does not associate errors with endpoints. Clients are expected to keep track of errors thrown. Clients can check if the error thrown is an error they expect.
* Conjure-Java serializes the error parameters as a `Map<String, String>` where the key is the parameter name, and the value is the toString representation of the parameter [(source)](https://github.com/palantir/conjure-java-runtime-api/blob/2.55.0/errors/src/main/java/com/palantir/conjure/java/api/errors/SerializableError.java#L126).
* This conflicts with the Conjure wire spec …

Support specifying errors on endpoints

---

docs/spec/conjure_definitions.md

The definitions mentions that "Union names MUST be in PascalCase", however the example given below had the union names in camelCase.
==COMMIT_MSG==
==COMMIT_MSG==
~The example now has union names in PascalCase, conforming to the aforementioned convention.~ The docs now mention that the union Names must be in camelCase.

Fix docs for union member casing

---

changelog/@unreleased/pr-1752.v2.yml
conjure-core/src/main/java/com/palantir/conjure/defs/validator/EndpointDefinitionValidator.java
conjure-core/src/test/java/com/palantir/conjure/defs/validator/EndpointDefinitionTest.java
conjure-core/src/test/resources/spec-tests/services.yml

Conjure endpoint validator allows nested containers in an endpoint query argument, for example: 
```
ArgumentDefinition:
type: optional<list<string>>
param-type: query
```
Query params cannot be nested container types, as container inner types must be serialized using PLAIN format, which only supports primitives + enums.
The example above in particular creates ambiguity in the wire format (since types with multiple elements are encoded to urls as a series of individual elements: `?arg=foo,arg=bar`, while optional types are simply omitted from the query string if the value is not present [[docs](https://palantir.github.io/conjure/#/docs/spec/wire?id=_22-query-parameters)]). In this case, an absence of the argument could be either the empty optional or a present optional with an empty list. …

Fix complex query param validation

---

conjure/src/main/java/com/palantir/conjure/cli/CliConfiguration.java
conjure/src/test/java/com/palantir/conjure/cli/ConjureCliTest.java

Conjure spec declares source files must end in `.yml` ([link](https://github.com/palantir/conjure/blob/c0b8383568ba01803bba7bad87c79d3ab2d3b7cf/docs/spec/conjure_definitions.md?plain=1#L3)). Filtering to YAML types when searching for inputs seems reasonable, filtering out hidden files feels overly prescriptive since its not explicitly declared in the spec. 
==COMMIT_MSG==
Filters input source files to YAML files.
==COMMIT_MSG==

Filters input files for YAML extensions
